In [2]:
a=1
b=2
c=a+b
print(c)


3


In [4]:
x = [0,1,2,3,4,5]
print(x[:2])
print(x[2:])

[0, 1]
[2, 3, 4, 5]


In [6]:
 x = [1,2,3]
 y = x
y[-1] = 4
print(x)


[1, 2, 4]


In [12]:
for i in range (5):
    if i >= 2: break
    print(i)

0
1


In [14]:
for i in range (5):
    if i == 2: continue
    print(i)

0
1
3
4


In [19]:
x = 3
if x > 3:
    print("too big")
elif x < 1:
    print("too small")
else:
    print("just right")

just right


In [21]:
a = 1
def f(x):
    return x+a # a is global variable
def g(x,a=1):
    return x+a # a is local variable
print(f(1))
print(g(1))
a = 2
print(f(1))
print(g(1))


2
2
3
2


In [22]:
import numpy as np
x = np.array ([1,2,3])
y = x
x += 1
print(y)
x[:] = x + 1
print(y)
x = x + 1
print(y)

[2 3 4]
[3 4 5]
[3 4 5]
